### ISSUE TITLE
Edit your attendace

### ISSUE THREAD

**Issue by sjain30** [collegeconnect/CollegeConnect#13]
Add the capability of editing the attendance of a particular subject i.e. the number of missed and the number of attended classes for that particular subject. After that the overall attendance should be calculated again automatically and update the attendance at the home page.

**Comment by sakshampruthi** [comment]
Also add an option to undo the last entry in popup menu under delete option

**Comment by arcanearronax** [comment]
If this item is unresolved, I'd like to make an attempt at this.

**Comment by sakshampruthi** [comment]
> If this item is unresolved, I'd like to make an attempt at this.

@arcanearronax  Sure, Go ahead. I'll assign it to you. If you have worked with room and live data I would recommend you to attempt this in MVVM branch

**Comment by sjain30** [comment]
@arcanearronax Any update on this feature?

**Comment by arcanearronax** [comment]
@sjain30 sorry for the delay, I should be done with it hopefully in the next week. Home and work life have been a bit more demanding than I expected.

**Comment by sjain30** [comment]
@arcanearronax, unfortunately, I have to unassign you from this issue since we needed this issue solved immediately I did it myself.
