### ISSUE TITLE
Hide Room Locator for colleges other than BVCOE

### ISSUE THREAD

**Issue by sjain30** [collegeconnect/CollegeConnect#15]
This issue can only be resolved after issue #8  is resolved.
In the tools section, hide room locator for colleges other than BVCOE

**Comment by bednarb** [comment]
This issue interests me and I'd like to attempt, can I assign it to myself?

**Comment by sakshampruthi** [comment]
@bednarb Yes Sure, you can go ahead and work on this. Try to implement it in MVVM branch if possible

**Comment by AkshatGadhwal** [comment]
hey can I get a more detailed description of the issue, I am not able to understand what to change?

**Comment by sakshampruthi** [comment]
@AkshatGadhwal I would suggest you join  [![Gitter](https://badges.gitter.im/CollegeConnect/discussion.svg)](https://gitter.im/CollegeConnect/discussion?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) for further discussions
