### ISSUE TITLE
Migrate SQLite Database to Room

### ISSUE THREAD

**Issue by sakshampruthi** [collegeconnect/CollegeConnect#27]

**Comment by nileshteji** [comment]
Is this issue resolved ?

**Comment by sakshampruthi** [comment]
@nileshteji No
You wish to work on it?

**Comment by nileshteji** [comment]
Yes i want to work on it

**Comment by sjain30** [comment]
Great! We'll assign it to you.
If you face any issue you can ask here or via email.

**Comment by nileshteji** [comment]
Cool @sjain30
