### ISSUE TITLE
New Edit Profile Interface

### ISSUE THREAD

**Issue by sjain30** [collegeconnect/CollegeConnect#42]
Design the Edit Profile section in the Settings Menu as per the design attached. 
Interested people can message us here and we'll mail you the necessary drawable files
![WhatsApp Image 2020-10-08 at 21 08 08](https://user-images.githubusercontent.com/43096728/96361758-0ab5c680-1146-11eb-97e4-c4bb6eccd30b.jpeg)

**Comment by root-ansh** [comment]
Can I work on this?  I would need help regarding those curved "edit profile"  background. Rest could be made. Also, what happens  on pressing the edit button? is there a popup or a different screen opens?

**Comment by efguydan** [comment]
I am interested in working on this. Can i get assigned?

**Comment by sakshampruthi** [comment]
@root-ansh Okay, you may work on this. Drop a message on Gitter for the vector background.
@efguydan If Ansh is unable to complete or he decides to drop it then I'll assign it to you.

**Comment by eashl003** [comment]
This looks interesting, and I would love to work on it! May I work on it?

**Comment by root-ansh** [comment]
@sakshampruthi  I will get it done by tomorrow night, if I couldn't then I will let you know

**Comment by efguydan** [comment]
@sjain30, can I get assigned to this now?

**Comment by sjain30** [comment]
Yes @efguydan please go ahead

**Comment by sjain30** [comment]
@eashl003 you can also try. Although we'll be putting out more ui/ux issues soon. If you're interested you can try those.

**Comment by efguydan** [comment]
Hello @sjain30 , what is the edit button expected to do? Open up a new screen?

**Comment by sjain30** [comment]
Just make it editable there only
