### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Faizi-alpha** [collegeconnect/CollegeConnect#46]
Can you guys help me with how you implemented the Notes fragment where the data from firebase storage is coming filtered w.r.t the input (Branch, unit , etc) provided by the user?

If there exist any article related to then would also help. But please do help me in implementing the functionality.

**Comment by sjain30** [comment]
Hi @Faizi-alpha 
The notes are not being filtered directly from firebase storage. The details of all the notes(including the download link) are stored in the database where the filtering takes place. You can look at the DownloadNotes.java file for the implementation.

**Comment by Faizi-alpha** [comment]
Sure, You guys have created a class Constants.java through which when a user uploads the files they go to the directory. But can you help me with how you guys are storing those addresses in the database `Upload upload = new Upload(filename,
                                        course.getSelectedItem().toString(),
                                        semester.getSelectedItem().toString(),
                                        branch.getSelectedItem().toString(),
                                        unit.getSelectedItem().toString(),
                                        authorname, 0, uri.toString(),
                                        System.currentTimeMillis(),
                                        SaveSharedPreference.getUserName(UploadNotes.this), new ArrayList() {
                                });`

**Comment by sakshampruthi** [comment]
Hi @Faizi-alpha , it would be great if we can continue this conversation on Gitter. This badge will redirect you to the same [![Gitter](https://badges.gitter.im/CollegeConnect/discussion.svg)](https://gitter.im/CollegeConnect/discussion?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) We would be happy to assist you there ✌✌
