### ISSUE TITLE
Add pdf viewer to view notes

### ISSUE THREAD

**Issue by sjain30** [collegeconnect/CollegeConnect#47]
At present on clicking on a note the app redirects outside the app. to In the Notes section and in the MyFiles section in the settings, integrate a pdf viewer to view the notes from within the app,

**Comment by TanishqSehgal7** [comment]
I can try to resolve this issue.

**Comment by sakshampruthi** [comment]
@TanishqSehgal7 Great I'll assign it to you.

**Comment by AvishekThapa1997** [comment]
Is this issue still open?

**Comment by sakshampruthi** [comment]
@AvishekThapa1997 this issue has already been assigned. If it does not get resolved we'll assign it you.

**Comment by AvishekThapa1997** [comment]
okay
